"""Inspect what a *real* DeepGEM label file would look like (for reference)."""
print('='*70)
print('代码分支决定的逻辑 (main/datasets/dataset_deepgem.py:99-122)')
print('='*70)
print('  - input_data 是 .csv    → 用 sample.csv 的 (0, 1) label, 忽略 --gene')
print('  - input_data 是 .pickle → 用 data_info[wsi_type][gene]["test"]')
print()
print('='*70)
print('真实基因预测需要的 pickle 结构 (作者内部数据格式)')
print('='*70)
print('data_info = {')
print('    "AspirationBiopsy": {')
print('        "EGFR":  { "train": {...}, "val": {...}, "test": {...} },')
print('        "KRAS":  { ... },')
print('        "TP53":  { ... },')
print('        "ALK":   { ... },')
print('        "ROS1":  { ... },')
print('        "LRP1B": { ... }')
print('    },')
print('    "ExcisionalBiopsy": { ... }')
print('}')
print()
print('='*70)
print('每个 (wsi_type, gene) 下的 test 块:')
print('='*70)
print('data_info["ExcisionalBiopsy"]["EGFR"]["test"] = {')
print('    "pid":   ["case_001", "case_002", ...],   # 几百个 WSI')
print('    "label": [1, 0, 1, 0, 1, ...]               # 这些 WSI 真实 EGFR 突变状态')
print('}')
print()
print('='*70)
print('现实')
print('='*70)
print('sample repo 没提供这种 pickle, 必须自己造或向作者申请')
print('csv demo 里 16 个 demo 都在用同一对 (0, 1), 所以严格说')
print('AUC=1.0 表示 "模型对 sample.csv 这对label预测对了",')
print('不代表 "该模型在 EGFR/KRAS/... 上真的准"')